POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "My new post with MongoDB",
  "postType": "post",
  "slug": "new-mongo-post",
  "status": "draft",
  "content": "post-content",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2024-03-16T07:46:32+0000",
  "tags": [
    "66d0a7288445603229511076",
    "66d5a3067eca866ac06973f3",
    "66d0a74a8445603229511078"
  ],
  "author": "66d07430b72373969a5c911c"
}