DELETE http://localhost:3000/posts/66d70fd85611d5c1eef5ec7f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmQ2MmIzYmZmYjYwMGNjMzIxYWUxM2QiLCJlbWFpbCI6InRpcmFtaXNzdUBqb2huLmNvbSIsImlhdCI6MTcyNTU2NTA4MiwiZXhwIjoxNzI1NTY4NjgyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.pEyqJ6potpEjLI7diF7Pc6mdwRzIMtVl4qepPC-AdJU