{{
    const date = new Date();
    exports.startDate = date.toString();
    exports.endDate = date.toString();

}}

GET  http://localhost:3000/posts
?limit=2
&page=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NmQ2MmIzYmZmYjYwMGNjMzIxYWUxM2QiLCJlbWFpbCI6InRpcmFtaXNzdUBqb2huLmNvbSIsImlhdCI6MTcyNTU2NTA4MiwiZXhwIjoxNzI1NTY4NjgyLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.pEyqJ6potpEjLI7diF7Pc6mdwRzIMtVl4qepPC-AdJU